// <auto-generated />
namespace aerables.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v0010 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v0010));
        
        string IMigrationMetadata.Id
        {
            get { return "201409251830591_v0010"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
